# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imovel',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço'),
        ),
    ]
